export const primaryColor = '#f53272'
export const textColor = '#fdfdfd'
export const buttonColor = '#f65f5c'
export const secundyColor = '#1f212c'
export const likeColor = '#3ef68b'
export const deslikeColor ='#ff1744'
export const check = '#3b96f3'
