POST http://localhost:3022/dog/createWalk
Content-Type: application/json

{
    "date" : "2022-04-11",
    "duration" : "30", 
    "petNumber": 5,
    "start" : "9", 
    "finish" : "18",
    "status" : "FINALIZADO"
}


###

GET http://localhost:3022/dog/




