GET http://localhost:3005/pokemon/by/400


###

GET http://localhost:3005/pokemon/family/18

###

GET http://localhost:3005/pokemon/generation/2


###

GET http://localhost:3005/pokemon/all/400/10

###

GET http://localhost:3005/pokemon/info/200

###

GET http://localhost:3005/pokemon/name
Content-Type: application/json

{
    "name": "Deoxys Attack"
}


